# Generated by Django 5.1.2 on 2025-01-25 23:26

import tables.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('id', models.CharField(default=tables.models.nid, max_length=200, primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='salevisit',
            fields=[
                ('date', models.IntegerField(blank=True, default=0, null=True)),
                ('id', models.CharField(default=tables.models.nid, max_length=200, primary_key=True, serialize=False)),
                ('partyName', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.CharField(blank=True, max_length=200, null=True)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('userid', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='party',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='date',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='status',
            field=models.CharField(blank=True, default='Active', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='userid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='isVisitOrder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='photo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='visitTime',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
